// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2KuJVlL3gaf4Ro-_PCc4dFa4GX5vTV2k',
    appId: '1:1089279774897:web:5a13a18c126877c8815290',
    messagingSenderId: '1089279774897',
    projectId: 'beacon-7004a',
    authDomain: 'beacon-7004a.firebaseapp.com',
    storageBucket: 'beacon-7004a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgW1NFp-Ka_R-5nVQ77W6G2p_SJWi3vt4',
    appId: '1:1089279774897:android:70c5dc419574613e815290',
    messagingSenderId: '1089279774897',
    projectId: 'beacon-7004a',
    storageBucket: 'beacon-7004a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlPAFiomAYhoFylz6ZsrCiS_WuLiBy_4',
    appId: '1:1089279774897:ios:69a39cb47622d881815290',
    messagingSenderId: '1089279774897',
    projectId: 'beacon-7004a',
    storageBucket: 'beacon-7004a.appspot.com',
    iosBundleId: 'com.example.beacon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2KuJVlL3gaf4Ro-_PCc4dFa4GX5vTV2k',
    appId: '1:1089279774897:web:c18074d8b247987d815290',
    messagingSenderId: '1089279774897',
    projectId: 'beacon-7004a',
    authDomain: 'beacon-7004a.firebaseapp.com',
    storageBucket: 'beacon-7004a.appspot.com',
  );
}
